#cloud-config

autoinstall:
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
        - country-mirror
        - uri: http://ca.archive.ubuntu.com/ubuntu/
    preserve_sources_list: false

  codecs:
    install: true

  drivers:
    install: true

  identity:
    hostname: fancy-lab-device-81
    password: "$6$9250e222c4c71f0c58d4c54b50a880a312e9f9fed55d5c3aa0b0e860ded99165"
    realname: usuario usuario
    username: usuario

  kernel:
    package: linux-generic-hwe-24.04

  keyboard:
    layout: us
    toggle: null
    variant: ''

  locale: en_US.UTF-8

  network:
    ethernets:
      enp1s0:
        dhcp4: true
    version: 2
    wifis: {}

  oem:
    install: auto

  source:
    id: ubuntu-desktop-minimal
    search_drivers: true

  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: false

  storage:
    layout:
      name: lvm
      sizing-policy: all
      match:
        serial: KINGSTON_SNV*

  timezone: Europe/Madrid

  updates: security

  version: 1
